- hosts: all
  tasks: []

- hosts: dokku
  vars_files:
    - ./vars/app-env.yaml

  roles:
    - { role: dokku_bot.ansible_dokku, become: yes }
    
  vars:
    dokku_plugins:
      - name: postgres
        url: https://github.com/dokku/dokku-postgres.git
    dokku_users:
      - name: vincent
        username: "{{ SSH_KEY_NAME }}"
        ssh_key: "{{ SSH_KEY_PUB }}"
    